# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenotice',
            name='TextContent',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
