# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170313_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenotice',
            name='ImageContent',
            field=models.FileField(default='NULL', upload_to='', verbose_name='ImageContent'),
        ),
    ]
