# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homenotice_imagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homenotice',
            name='ImageContent',
        ),
    ]
