# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionAmount', models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Amount')),
                ('BalanceAfterTransaction', models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Balance')),
                ('TransactionDateTime', models.DateTimeField(verbose_name='Date & Time')),
                ('TransactionComment', models.CharField(max_length=75, verbose_name='Comment')),
            ],
        ),
    ]
