# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='TransactionFrom',
            field=models.CharField(default='x', max_length=75, verbose_name='From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='TransactionTo',
            field=models.CharField(default='x', max_length=75, verbose_name='To'),
            preserve_default=False,
        ),
    ]
