# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('WalletJournal', '0002_auto_20170310_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='BalanceAfterTransaction',
            field=models.FloatField(max_length=75, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TransactionAmount',
            field=models.FloatField(max_length=75, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Amount'),
        ),
    ]
