# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletJournal', '0004_auto_20170311_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTotalInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharacterName', models.CharField(max_length=75, verbose_name='Character Name')),
                ('TotalInvestment', models.FloatField(max_length=75, verbose_name='Total Investment')),
            ],
        ),
        migrations.CreateModel(
            name='PastTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefID', models.CharField(max_length=75, verbose_name='RefID')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharacterName', models.CharField(max_length=75, verbose_name='From')),
                ('PaymentAmount', models.FloatField(max_length=75, verbose_name='Payment Amount')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='BalanceAfterTransaction',
            field=models.CharField(max_length=75, verbose_name='Balance'),
        ),
    ]
