# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletJournal', '0005_auto_20170314_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalInvestors', models.IntegerField(max_length=75, verbose_name='Total Investors')),
                ('TotalInvestments', models.FloatField(max_length=75, verbose_name='Total Invested Value')),
                ('AverageInvestment', models.FloatField(max_length=75, verbose_name='Average Investment')),
                ('TotalDividendsPaid', models.FloatField(max_length=75, verbose_name='Total Dividends Paid')),
                ('TotalISKLeft', models.FloatField(max_length=75, verbose_name='Total ISK Left')),
                ('NextDivPayment', models.FloatField(max_length=75, verbose_name='Next Dividend Payment')),
            ],
        ),
    ]
