# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletJournal', '0006_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='TotalInvestors',
            field=models.IntegerField(verbose_name='Total Investors'),
        ),
    ]
