# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletJournal', '0007_auto_20170317_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertotalinvestment',
            name='LastRefferalAmount',
            field=models.FloatField(default=0, max_length=75, verbose_name=b'Last Refferal Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertotalinvestment',
            name='RefferalBalance',
            field=models.FloatField(default=0, max_length=75, verbose_name=b'Refferal Balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertotalinvestment',
            name='Refferals',
            field=models.IntegerField(default=0, verbose_name=b'Number of Refferals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='TotalRefferalsPaid',
            field=models.FloatField(default=0.0, max_length=75, verbose_name=b'Total Refferals Paid'),
            preserve_default=False,
        ),
    ]
